#!/usr/bin/env python3
"""
build_schools.py — build a compact REAL California public-school dataset for the
CA School Finder web app, from the CA Dept. of Education public school directory.

Input  : pubschls.txt  (tab-separated; download below)
Output : ../data/schools.js   -> sets window.SCHOOLS = [...]

Download the source (no key needed):

    curl -o pubschls.txt \
      "https://www.cde.ca.gov/schooldirectory/report?rid=dl1&tp=txt"

We keep only ACTIVE, regular (non-charter, attendance-based) schools with valid
coordinates, classify each as Elementary / Middle / High from the grade span,
and emit name, district, city, zip, lat, lon, grades, and a stable CDS id.
Ratings/history are modeled at runtime (seeded by the CDS id) and badged in-UI.
"""

import csv, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "pubschls.txt")
OUT = os.path.join(HERE, "..", "data", "schools.js")

# SOCType values we treat as regular attendance schools (per level).
ALLOWED_SOC = {
    "Elementary Schools (Public)",
    "Elementary School in 1 School District (Public)",
    "Intermediate/Middle Schools (Public)",
    "Junior High Schools (Public)",
    "High Schools (Public)",
    "High Schools in 1 School District (Public)",
    "K-12 Schools (Public)",
}

# Educational-program types that are NOT comprehensive attendance schools
# (continuation, alternative, court/community day, special-ed, etc.). Excluding
# these keeps "assigned = nearest regular school" from picking a tiny alt school.
EXCLUDE_EDOPS = {
    "Continuation School",
    "Alternative School of Choice",
    "Opportunity School",
    "County Community School",
    "Community Day School",
    "Juvenile Court School",
    "Special Education School",
    "Home and Hospital",
    "State Special School",
    "District Community Day School",
    "County Office of Education (COE)",
}


def grade_to_num(x):
    x = x.strip().upper()
    if x in ("K", "P", "PS", "TK", "KG", "PK"):
        return 0
    try:
        return int(x)
    except ValueError:
        return None


def classify(gs):
    """Return 'Elementary' | 'Middle' | 'High' | None from a grade span like K-5."""
    gs = (gs or "").strip()
    if not gs:
        return None
    parts = gs.split("-")
    lo = grade_to_num(parts[0])
    hi = grade_to_num(parts[-1]) if len(parts) > 1 else lo
    if lo is None or hi is None:
        return None
    # K-12 / very wide spans -> treat by presence; prefer High if includes 9-12
    if lo <= 5 and hi <= 5:
        return "Elementary"
    if lo >= 9:
        return "High"
    if 6 <= lo and hi <= 8:
        return "Middle"
    if lo <= 5 and 6 <= hi <= 8:
        return "Elementary"      # K-8 -> counts as elementary feeder
    if lo <= 8 and hi >= 9:
        return "High"            # spans into high school
    if hi <= 8:
        return "Middle"
    return None


def main():
    if not os.path.exists(SRC):
        sys.exit(f"Missing input {SRC}. Download pubschls.txt first (see header).")

    out = []
    with open(SRC, encoding="latin-1", newline="") as f:
        r = csv.DictReader(f, delimiter="\t")
        for d in r:
            if d.get("StatusType") != "Active":
                continue
            if (d.get("Charter") or "").strip() == "Y":
                continue
            soc = (d.get("SOCType") or "").strip()
            if soc not in ALLOWED_SOC:
                continue
            edops = (d.get("EdOpsName") or "").strip()
            if edops in EXCLUDE_EDOPS:
                continue
            try:
                lat = float(d["Latitude"])
                lon = float(d["Longitude"])
            except (KeyError, ValueError, TypeError):
                continue
            gs = (d.get("GSserved") or d.get("GSoffered") or "").strip()
            level = classify(gs)
            if not level:
                continue
            out.append({
                "id": d.get("CDSCode", "").strip(),
                "name": (d.get("School") or "").strip(),
                "district": (d.get("District") or "").strip(),
                "city": (d.get("City") or "").strip(),
                "zip": (d.get("Zip") or "").strip()[:5],
                "level": level,
                "grades": gs,
                "lat": round(lat, 6),
                "lon": round(lon, 6),
            })

    # de-dup by id
    seen, uniq = set(), []
    for s in out:
        if s["id"] and s["id"] not in seen:
            seen.add(s["id"])
            uniq.append(s)

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("/* AUTO-GENERATED by scripts/build_schools.py — REAL CA DOE data. */\n")
        f.write("window.SCHOOLS = ")
        json.dump(uniq, f, separators=(",", ":"))
        f.write(";\n")

    by = {}
    for s in uniq:
        by[s["level"]] = by.get(s["level"], 0) + 1
    print(f"Wrote {len(uniq)} schools -> {OUT}")
    print("By level:", by)


if __name__ == "__main__":
    main()
