#!/usr/bin/env python3
"""
build_accountability.py — REAL CA School Dashboard indicators per school.

Parses the CA Dashboard research files (tab-delimited, shared schema) and
extracts the school-level ("rtype"=="S"), All-students ("studentgroup"=="ALL")
current values, producing REAL:

  - graduation %          from graddownload<year>.txt   (currstatus)
  - chronic absenteeism % from chronicdownload<year>.txt (currstatus)
  - attendance %          = 100 - chronic
  - college/career %      from ccidownload<year>.txt     (currstatus, % Prepared)
  - academic progress     = mean of ELA & Math DFS "change"
                            from eladownload/mathdownload (change; points)

Shared columns (0-based): cds=0, rtype=1, studentgroup=8, currstatus=11, change=15.

Input : /tmp/{grad,chronic,cci,ela,math}download<year>.txt  (download from
        https://www3.cde.ca.gov/researchfiles/cadashboard/)
Output: ../data/accountability.js -> window.SCHOOL_ACCT = {
          "<CDS>": { grad, chronic, attend, college, acadProg, year }
        }
"""

import csv, os, sys, json

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "data", "accountability.js")
YEAR = sys.argv[1] if len(sys.argv) > 1 else "2025"
SRC = "/tmp"

C_CDS, C_RTYPE, C_GROUP, C_STATUS, C_CHANGE = 0, 1, 8, 11, 15


def num(x):
    x = (x or "").strip()
    if x in ("", "*", "N/A", "NA"):
        return None
    try:
        return float(x)
    except ValueError:
        return None


def read_metric(fname, want="status", cstat=C_STATUS, cchg=C_CHANGE):
    """Return {cds: value} for school/ALL rows (currstatus or change).

    Column positions differ by file:
      grad/chronic/cci : currstatus=11, change=15 (0-based)
      ela/math         : currstatus=10, change=13 (0-based)  [no currnumer col]
    """
    path = os.path.join(SRC, fname)
    out = {}
    need = cstat if want == "status" else cchg
    if not os.path.exists(path):
        print(f"  (missing {fname})")
        return out
    with open(path, encoding="latin-1", newline="") as f:
        r = csv.reader(f, delimiter="\t")
        next(r, None)
        for row in r:
            if len(row) <= max(cstat, cchg, C_GROUP):
                continue
            if row[C_RTYPE] != "S" or row[C_GROUP] != "ALL":
                continue
            cds = row[C_CDS].strip().zfill(14)
            v = num(row[need])
            if v is not None:
                out[cds] = v
    return out


def main():
    grad = read_metric(f"graddownload{YEAR}.txt", "status")
    chronic = read_metric(f"chronicdownload{YEAR}.txt", "status")
    cci = read_metric(f"ccidownload{YEAR}.txt", "status")
    # ELA/Math academic files use currstatus=10, change=13 (0-based).
    ela_ch = read_metric(f"eladownload{YEAR}.txt", "change", 10, 13)
    math_ch = read_metric(f"mathdownload{YEAR}.txt", "change", 10, 13)
    ela_st = read_metric(f"eladownload{YEAR}.txt", "status", 10, 13)  # DFS (current)
    math_st = read_metric(f"mathdownload{YEAR}.txt", "status", 10, 13)

    cds_all = (set(grad) | set(chronic) | set(cci) | set(ela_ch) | set(math_ch)
               | set(ela_st) | set(math_st))
    out = {}
    for cds in cds_all:
        rec = {"year": int(YEAR)}
        if cds in grad:
            rec["grad"] = round(grad[cds], 1)
        if cds in chronic:
            rec["chronic"] = round(chronic[cds], 1)
            rec["attend"] = round(100 - chronic[cds], 1)
        if cds in cci:
            rec["college"] = round(cci[cds], 1)
        e, m = ela_ch.get(cds), math_ch.get(cds)
        vals = [x for x in (e, m) if x is not None]
        if vals:
            rec["acadProg"] = round(sum(vals) / len(vals), 1)  # DFS points change
        if cds in ela_st:
            rec["elaDFS"] = round(ela_st[cds], 1)   # ELA Distance from Standard (pts)
        if cds in math_st:
            rec["mathDFS"] = round(math_st[cds], 1)
        out[cds] = rec

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("/* AUTO-GENERATED by scripts/build_accountability.py — REAL CA Dashboard "
                f"{YEAR}.\n   grad/chronic/attend/college in %, acadProg = mean ELA+Math "
                "DFS change (points). */\n")
        f.write("window.SCHOOL_ACCT = ")
        json.dump(out, f, separators=(",", ":"))
        f.write(";\n")
    print(f"grad={len(grad)} chronic={len(chronic)} cci={len(cci)} "
          f"ela_ch={len(ela_ch)} math_ch={len(math_ch)} -> {len(out)} schools")
    print("Wrote", OUT)


if __name__ == "__main__":
    main()
